services:
  server:
    container_name: main_server_dev
    build:
      context: ./
      dockerfile: ./server/Dockerfile
      target: development
    ports:
      - "4000:4000"
    env_file:
      - ./server/.env
    volumes:
      - ./server:/usr/src/app/server
      - server_node_modules:/usr/src/app/server/node_modules

  client:
    container_name: main_client_dev
    build:
      context: ./
      dockerfile: ./client/Dockerfile
      target: development
    ports:
      - "4200:4200"
    volumes:
      - ./client:/usr/src/app/client
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  server_node_modules:
